logging:
  version: 1
  disable_existing_loggers: false
  formatters:
    default:
      format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
  handlers:
    console:
      class: logging.StreamHandler
      level: INFO
      formatter: default
      stream: ext://sys.stdout
  root:
    level: INFO
    handlers: [ console ]

risk:
  noise_level: 2.0
  weights:
    crime_index: 1.0
    accident_rate: 1.0
    socioeconomic_level: 1.0
    weather_condition:
      sunny: 2.0
      rain: 4.0
      snow: 6.0
      armageddon: 9.0